import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/services/AuthProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: '400' });
const robo = Roboto({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={poppins.className}>{children}</body> */}
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
      {/* <body className={robo.className}>{children}</body> */}
    </html>
  );
}
